2019-12-17 15:29:20,273 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 15:30:00,557 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 15:31:55,636 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 15:32:04,914 ERROR: Exception on /index [POST] [in /Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jboucas/flask_dashboard/app/routes.py", line 244, in index
    fig=make_figure(df,plot_arguments)
  File "/Users/jboucas/flask_dashboard/app/routes.py", line 46, in make_figure
    fig=plt.figure(figsize(6,6))
NameError: name 'figsize' is not defined
2019-12-17 15:32:51,563 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 15:42:39,309 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 16:02:41,514 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 16:03:18,802 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 16:04:04,661 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 16:06:13,035 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:12:57,640 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:17:11,334 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:18:39,112 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:19:26,857 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:19:52,827 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:21:38,826 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:22:35,745 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:30:36,648 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:31:06,880 ERROR: Exception on /index [POST] [in /Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jboucas/flask_dashboard/app/routes.py", line 242, in index
    return render_template('index.html', maxHeightSideBar=maxHeightSideBar , filename=filename, sometext=sometext, **plot_arguments)
UnboundLocalError: local variable 'maxHeightSideBar' referenced before assignment
2019-12-17 20:31:58,452 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:34:12,976 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:40:19,268 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:40:25,972 ERROR: Exception on /index [POST] [in /Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jboucas/flask_dashboard/app/routes.py", line 242, in index
    return render_template('index.html', maxHeightSideBar=maxHeightSideBar , filename=filename, sometext=sometext, **plot_arguments)
UnboundLocalError: local variable 'maxHeightSideBar' referenced before assignment
2019-12-17 20:40:32,477 ERROR: Exception on /index [POST] [in /Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jboucas/flask_dashboard/app/routes.py", line 242, in index
    return render_template('index.html', maxHeightSideBar=maxHeightSideBar , filename=filename, sometext=sometext, **plot_arguments)
UnboundLocalError: local variable 'maxHeightSideBar' referenced before assignment
2019-12-17 20:41:18,837 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:43:23,866 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:43:53,821 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:44:09,310 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:44:40,510 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:45:07,868 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:45:36,850 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:45:56,168 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:46:37,332 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:48:04,980 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:48:40,185 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:49:15,725 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:49:43,319 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:50:35,745 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:51:03,054 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:51:22,975 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:51:44,385 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 20:52:08,471 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
